---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: kube-system
# eyJhbGciOiJSUzI1NiIsImtpZCI6ImY2UW4yakZwSUVSZlRELUNSZG9YV3VTUWlmYWlPM0YyRU9KQU1BdDVjbkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJnaXRsYWItYWRtaW4tdG9rZW4taGc3azQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ2l0bGFiLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTFlNmMwMTQtYmQ5Yy00MTA1LWExNWQtNzEyOWZiODY3OGQ2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmdpdGxhYi1hZG1pbiJ9.psB7GjGdLZrg31PrFWhpupsvwcBhFrvcWsERvsoEPkfhUInFZ3oeICGlYfVSkrgBpcOFvDSpMJbeJvwkqWWnvewo8I4x_v0Mjawn_Ht9lL3s-d-kfP478ZJexwlQ39ayfDQXt8oLeajO29PthIiTpfhBEtz4wzgPTZLplD0TjjkCyarnalUGQK_y-KGjR39FhSd-rfHYDELuyc7Gd2K8NSg06jsFvK90aNG0WhycOkj7vOdq9Ua32MU8Q06TEpjEaaadzsco3lOvA84Oui6cExy6MElNEwC5OYKN0aYzKqrxLw7AtCr-CYmecoVzI6X5Zv-quMpZa-lwOO09yTmwyw%
# https://51.250.95.117
# -----BEGIN CERTIFICATE-----\nMIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\ncm5ldGVzMB4XDTIyMDYyNzA5MTU1N1oXDTMyMDYyNDA5MTU1N1owFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMES\nusw0tGCVwKkp56F7fSa9RiyakW35oU7c9aZFdNxd38M9l1gRc0hPL9P18Hx4ZDpw\nK7sAkpNyxN3wGJd55h9naufRHzF60SooWVDNranzTf/S1V+VZZitdzLDo+lsCvIA\n+U4bRvISXdUjoeUNe/dXM3XtS8JgkVen5OJWkvfbLFRweq5KoqoJNRNZqE9MW0aY\n5mKhhwD/zYzCyk4HxfCNdpj7p1YH8VMPGzVDw3/69OjMRSJ55CXQsO9xct0icQYo\nH4GG2IJX+qzFFyfbmtMFHKij96Xole7JQkRTh1tqR7s9YQAEm0PrZhC1fHb6/eVa\n2x2OfVPcjkEqgdh4YOcCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\n/wQFMAMBAf8wHQYDVR0OBBYEFNdaXwlLEHYdGQig2cnYbHvHw93cMA0GCSqGSIb3\nDQEBCwUAA4IBAQAS9UrPcYP4yvfHqm4Kjrpw0O/KTpBm74al0PsYDbLGGTMjDe0E\nDFCr5VxWVmpOSGGaTyXM/KIboi3o1xISGOStVF5HfNBlbAU+LgajGe4peLJ0M1dc\ngNiRjxXrSAaju6ShcbMuAiJX1Ohvlxgt3ll2y3/WPTJN3a+cMMKTDyB9FmrgJwvl\ngCalQQ25bv64GWqJHJoHM9eCziC7QIhk1XXHbnXNx1fBKkkhe2dwnDeczv/5M9mg\nLUngboY2sXUNe8MG1Gg9dBfxsOD0NogjT9LEA96/v1xhbjbl5cPEF9VW2J3i9Fi0\n62fPaoIrAt/eUL5KH4Q/UDRzroHAHtMp49+1\n-----END CERTIFICATE-----\n

# http://51.250.4.163/
# GR1348941MK9XiAHqtT9Yxbqzsn2F
